server:
  port: 4500
  error:
    include-message: always
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/StudentDB
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
